### PR TITLE
Spanish Translation

### PR DESCRIPTION
**Pull request by AdamIsmael**
Hello,

I'm not a native speaker but I've been learning in my spare time for 4 years. There are no doubt grammatical errors and sentences that are a bit strange but I believe the basic meaning is put across.
I'd welcome any improvements.

Adam

### CODE REVIEW

**Comment by PandawanFr** [comment]
Awesome work, but there is one small problem, we already have a Spanish translation... 

Feel free to edit the current pages, but I don't know if there is a real need to overwrite them/start over. Also, I added a couple of new pages which might not be translated, but I don't understand why you went ahead and did all of this.

**Comment by AdamIsmael** [comment]
Either I didn't notice the translation or someone beat me to it. I did it mainly for my own practice so not to worry. I'll look again and see if there is any untranslated pages.

**Comment by AdamIsmael** [comment]
Could I ask what technologies you used to make this website?

**Comment by PandawanFr** [comment]
The entire source code of the website is available on this GitHub repo. But here's a list of things that I used:

- Node/NPM (packages/project)
- Gulp (building the site)
- EJS (dynamic page creationg)
- Bulma (CSS framework)

Now I don't really recommend that you use Gulp and EJS anymore as they are a bit outdated... Consider using something like [React](https://reactjs.org/) or [Vue](https://vuejs.org/). But you can still try if you want.

**Comment by AdamIsmael** [comment]
Okay, thank you for your response and advice. How did you go about deploying the site?

**Comment by PandawanFr** [comment]
So I upload my site content to GitHub and use a separate branch `gh-pages` for GitHub Pages. (You can learn more about GitHub Pages [here](https://pages.github.com/)).

Although the site at [guide.garli.co.in](https://guide.garli.co.in/) is a CI made by Vilsol which auto-builds whenever I push a commit to GitHub (meaning that they are technically different sites but with the same code).

Lastly, if you meant how I go about uploading to GitHub pages and everything, I have a task on Gulp called `deploy` which uses the npm package [gh-pages](https://www.npmjs.com/package/gh-pages) to auto upload my `dist` folder to the new branch after building everything.

**Pull request closed without merging**
